### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by Kyanoxia** [Windows81/zyBook-Crook#2]
I've come across a few projects like this in which we're given a js file.  How does one run this, using NPM?  I'm just a bit confused here.

**Comment by Windows81** [comment]
I think you'd use `npm start`.  Otherwise, try `node main.js`, where
`main.js` is the file name.

**Comment by Windows81** [comment]
Even then, I don't think it'd work anymore.  They might've changed the
checksum function.

**Comment by Kyanoxia** [comment]
Thanks
